GuideConst = {}

GuideConst.GUIDE_NOTIFY = {
    EVENT = 1,
    INIT = 2,
    UPDATE = 3
}

GuideConst.GUIDE_EVENT = {
    UI_VIEW_ENTER = "UI_VIEW_ENTER",
    UI_VIEW_EXIT = "UI_VIEW_EXIT",
    UI_VIEW_REFRESH = "UI_VIEW_REFRESH",
    UI_VIEW_ENTER_ANI_END = "UI_VIEW_ENTER_ANI_END",
    EVENT_RECONNECT_SUCCESS = "EVENT_RECONNECT_SUCCESS",
    CUSTOM_EVENT = "CUSTOM_EVENT",
}

GuideConst.CUSTOM_EVENT = {
    FIGHT_SERVER_START = "FIGHT_SERVER_START",
    FIGHT_START = "FIGHT_START",
    FIGHT_FINISH = "FIGHT_FINISH",
    FIGHT_USE_SKILL = "FIGHT_USE_SKILL",
    GUIDE_FIGHT_START = "GUIDE_FIGHT_START",
    FIGHT_HAND_SPRITE = "FIGHT_HAND_SPRITE",
    FIGHT_ENEGY_CHANGE = "FIGHT_ENEGY_CHANGE",
    FIGHT_OWN_TOWER_HITTED = "FIGHT_OWN_TOWER_HITTED",
    FIGHT_ENEMY_TOWER_HITTED = "FIGHT_ENEMY_TOWER_HITTED",
    FIGHT_OWN_BUILD_HITTED = "FIGHT_OWN_BUILD_HITTED",
    FIGHT_ENEMY_BUILD_HITTED = "FIGHT_ENEMY_BUILD_HITTED",

    ENTER_LIFE_TREE = "ENTER_LIFE_TREE",
    ENTER_LIFE_TREE_FINISH = "ENTER_LIFE_TREE_FINISH",

	PVP_BOX_FINISH = "PVP_BOX_FINISH",
	REFRESH_CARD_MALL_FINISH = "REFRESH_CARD_MALL_FINISH",
	SET_MAIN_CARD_FINISH = "SET_MAIN_CARD_FINISH" ,
	SET_SUB_CARD_FINISH = "SET_SUB_CARD_FINISH",
}

GuideConst.ConditionType = {
    FUNC = 1,
    OBJ = 2,
}

GuideConst.MASK_NODETYPE = 
{
	LAYOUT = "LAYOUT", -- 面板
	NOTNODE = "NULL", -- 空
    POLYGON = "POLYGON", -- 多边形
    CYCLE = "CYCLE", -- 圆
    RECT = "RECT", -- 方形
}

GuideConst.GroupType = {
    GUIDE = 1,
    STORY = 2,
}

GuideConst.OnGlobalEvent = "OnGlobalEvent" 

return GuideConst